# Generated by Django 4.2.2 on 2023-07-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('ph', models.FloatField()),
                ('termo', models.FloatField()),
                ('condu', models.FloatField()),
                ('otroSensor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Watersample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('ph', models.FloatField()),
                ('termo', models.FloatField()),
                ('condu', models.FloatField()),
                ('otroSensor', models.FloatField()),
            ],
        ),
    ]
