# Generated by Django 4.2.2 on 2023-07-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadistics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelprofile',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='modelprofile',
            name='condu',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='modelprofile',
            name='otroSensor',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='modelprofile',
            name='ph',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='modelprofile',
            name='termo',
            field=models.FloatField(default=0.0),
        ),
    ]
