# Generated by Django 4.2.3 on 2023-07-08 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_users_options_alter_users_managers_and_more'),
        ('stadistics', '0002_remove_modelprofile_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersample',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.users'),
        ),
    ]
