# Generated by Django 4.2.3 on 2023-07-08 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_users_id'),
        ('stadistics', '0004_remove_watersample_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersample',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='watersamples', to='Users.users'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watersample',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
