# Generated by Django 4.2.3 on 2023-07-08 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stadistics', '0005_watersample_user_alter_watersample_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watersample',
            old_name='user',
            new_name='user_id',
        ),
    ]
