# Generated by Django 4.2.3 on 2023-07-08 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stadistics', '0006_rename_user_watersample_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watersample',
            old_name='user_id',
            new_name='user',
        ),
    ]
